# Generated by Django 5.0.4 on 2024-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Turkish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Turkish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Turkish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Turkish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Turkish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_collation='Turkish_CI_AS', db_column='CustomerName', max_length=100)),
                ('budget', models.DecimalField(blank=True, db_column='Budget', decimal_places=2, max_digits=10, null=True)),
                ('customertype', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='CustomerType', max_length=10, null=True)),
                ('totalspent', models.DecimalField(blank=True, db_column='TotalSpent', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Turkish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Turkish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Turkish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Turkish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Turkish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logadmin',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('islemdurumu', models.BooleanField(db_column='IslemDurumu')),
                ('islem', models.CharField(db_collation='Turkish_CI_AS', db_column='Islem', max_length=50)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('degisen', models.CharField(db_collation='Turkish_CI_AS', db_column='Degisen', max_length=255)),
            ],
            options={
                'db_table': 'LogAdmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('logdate', models.DateTimeField(blank=True, db_column='LogDate', null=True)),
                ('logtype', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='LogType', max_length=20, null=True)),
                ('logdetails', models.TextField(blank=True, db_collation='Turkish_CI_AS', db_column='LogDetails', null=True)),
            ],
            options={
                'db_table': 'Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('totalprice', models.DecimalField(blank=True, db_column='TotalPrice', decimal_places=2, max_digits=10, null=True)),
                ('orderdate', models.DateTimeField(blank=True, db_column='OrderDate', null=True)),
                ('orderstatus', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='OrderStatus', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessappLogentry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
                ('action', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
                ('date', models.DateTimeField()),
                ('ip', models.CharField(db_collation='Turkish_CI_AS', max_length=39)),
                ('status', models.CharField(db_collation='Turkish_CI_AS', max_length=50)),
                ('detail', models.TextField(db_collation='Turkish_CI_AS')),
            ],
            options={
                'db_table': 'processApp_logentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_collation='Turkish_CI_AS', db_column='ProductName', max_length=100)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
    ]
