# Generated by Django 5.0.4 on 2024-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditModeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_edit_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
