# Generated by Django 5.0.4 on 2024-12-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0002_editmodesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requestdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('priority_score', models.IntegerField(default=0)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processApp.customers')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processApp.products')),
            ],
            options={
                'db_table': 'pending_orders',
            },
        ),
    ]
