# Generated by Django 5.0.4 on 2024-12-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0003_pendingorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logadmin',
            options={'managed': True},
        ),
    ]
