# Generated by Django 5.0.4 on 2024-12-25 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processApp', '0005_alter_logadmin_degisen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='related_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processApp.orders'),
        ),
    ]
